/**
 * Memory API — REST endpoints for Overlord memory management.
 * Bridges browser store → Obsidian vault → Cognee knowledge graph.
 */
import { NextRequest, NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import os from 'os';

const execAsync = promisify(exec);

const VAULT_DIR = path.join(os.homedir(), 'wiki', 'overlord-memories');
const BRIDGE_SCRIPT = path.join(os.homedir(), '.hermes', 'scripts', 'obsidian_bridge.py');

// ─── Helpers ────────────────────────────────────────────────────────────────

function sanitizeFilename(text: string, maxLen = 60): string {
  return text
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, ' ')
    .slice(0, maxLen)
    .trim();
}

function memoryToMarkdown(entry: any): string {
  const date = new Date(entry.timestamp || Date.now());
  const dateStr = date.toISOString().replace('T', ' ').slice(0, 16);
  const tags = entry.tags || [];
  const source = entry.source || 'overlord';
  const memType = entry.type || 'fact';

  const frontmatter = [
    '---',
    `created: ${dateStr}`,
    `source: ${source}`,
    `type: ${memType}`,
    `tags: [${tags.join(', ')}]`,
    `memory_id: ${entry.id}`,
    '---',
  ].join('\n');

  return [
    frontmatter,
    '',
    `## ${memType.charAt(0).toUpperCase() + memType.slice(1)}: ${(entry.content || '').slice(0, 80)}`,
    '',
    entry.content || '',
    '',
    tags.length ? '## Tags\n' + tags.map((t: string) => `- #${t}`).join('\n') + '\n' : '',
    `*Source: ${source} | Created: ${dateStr}*`,
    '',
  ].join('\n');
}

async function ensureVaultDir() {
  await fs.mkdir(VAULT_DIR, { recursive: true });
}

async function writeObsidianEntry(entry: any): Promise<string> {
  await ensureVaultDir();
  
  const datePrefix = new Date(entry.timestamp || Date.now())
    .toISOString().slice(0, 10);
  const contentPreview = sanitizeFilename(entry.content || 'memory');
  const filename = `${datePrefix} - ${contentPreview}.md`;
  const filepath = path.join(VAULT_DIR, filename);

  await fs.writeFile(filepath, memoryToMarkdown(entry), 'utf-8');

  // Update index
  await updateIndex(entry, filename);

  return filename;
}

async function updateIndex(entry: any, filename: string): Promise<void> {
  const indexPath = path.join(VAULT_DIR, 'Memory Index.md');
  const dateStr = new Date(entry.timestamp || Date.now())
    .toISOString().replace('T', ' ').slice(0, 16);
  const tagsStr = (entry.tags || []).join(', ');
  const contentPreview = (entry.content || '').slice(0, 60);
  
  const line = `- [[${filename}]] | ${dateStr} | ${entry.source || 'overlord'} | ${contentPreview}... | ${tagsStr}\n`;

  let existing = '';
  try {
    existing = await fs.readFile(indexPath, 'utf-8');
  } catch {
    existing = '# Memory Index\n\nAll memories generated by Overlord agents.\n\n| File | Date | Source | Content | Tags |\n|------|------|--------|---------|------|\n';
  }

  if (existing.includes(line.trim())) return;

  await fs.writeFile(indexPath, existing + line, 'utf-8');
}

async function findMemoryFileById(id: string): Promise<string | null> {
  try {
    const files = await fs.readdir(VAULT_DIR);
    for (const file of files) {
      if (file === 'Memory Index.md' || !file.endsWith('.md')) continue;
      const content = await fs.readFile(path.join(VAULT_DIR, file), 'utf-8');
      if (content.includes(`memory_id: ${id}`)) return file;
    }
  } catch { /* not found */ }
  return null;
}

async function triggerCogneeSync(): Promise<void> {
  // Fire-and-forget cognify trigger for new memory
  const script = path.join(os.homedir(), '.hermes', 'scripts', 'cognee_run.sh');
  execAsync(`${script} --cognify-only`).catch(() => {
    // Swallow — cognify is best-effort, can retry next time
  });
}

// ─── GET: List memories (from Obsidian vault) ───────────────────────────────

export async function GET() {
  try {
    await ensureVaultDir();
    const files = await fs.readdir(VAULT_DIR);
    
    const memories: any[] = [];
    for (const file of files) {
      if (file === 'Memory Index.md' || !file.endsWith('.md')) continue;
      
      const content = await fs.readFile(path.join(VAULT_DIR, file), 'utf-8');
      
      // Parse frontmatter
      const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
      if (!fmMatch) continue;
      
      const fmText = fmMatch[1];
      const source = fmText.match(/^source:\s*(.+)/m)?.[1] || 'overlord';
      const typeMatch = fmText.match(/^type:\s*(.+)/m)?.[1] || 'fact';
      const tagsMatch = fmText.match(/^tags:\s*\[(.+)\]/m)?.[1] || '';
      const idMatch = fmText.match(/^memory_id:\s*(.+)/m)?.[1] || '';
      const createdMatch = fmText.match(/^created:\s*(.+)/m)?.[1] || '';
      
      // Extract body (after second ---)
      const body = content.replace(/^---\n[\s\S]*?\n---\n*/, '').trim();
      
      memories.push({
        id: idMatch || file,
        filename: file,
        source,
        type: typeMatch,
        tags: tagsMatch ? tagsMatch.split(', ').map(t => t.trim()).filter(Boolean) : [],
        content: body.replace(/^## .+\n*/, '').replace(/\*Source: .+$/, '').trim(),
        createdAt: createdMatch || null,
      });
    }

    // Sort by date descending
    memories.sort((a, b) => new Date(b.createdAt || '').getTime() - new Date(a.createdAt || '').getTime());

    return NextResponse.json({ success: true, memories, count: memories.length });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}

// ─── POST: Create new memory ────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { content, source = 'Rich', type = 'fact', tags = [], timestamp = Date.now(), id = `mem_${Date.now()}` } = body;

    if (!content) {
      return NextResponse.json({ success: false, error: 'Content required' }, { status: 400 });
    }

    const entry = { id, content, source, type, tags, timestamp };

    // Write to Obsidian vault
    const filename = await writeObsidianEntry(entry);

    // Trigger Cognee cognify (async, fire-and-forget)
    await triggerCogneeSync();

    return NextResponse.json({
      success: true,
      message: `Memory saved to Obsidian: ${filename}`,
      memory: { ...entry, filename },
    });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}

// ─── DELETE: Remove memory ──────────────────────────────────────────────────

export async function DELETE(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const id = searchParams.get('id');
    
    if (!id) {
      return NextResponse.json({ success: false, error: 'ID required' }, { status: 400 });
    }

    const file = await findMemoryFileById(id);
    if (!file) {
      return NextResponse.json({ success: false, error: 'Not found' }, { status: 404 });
    }

    await fs.unlink(path.join(VAULT_DIR, file));

    // Trigger cognify to update graph
    await triggerCogneeSync();

    return NextResponse.json({ success: true, memory: `Deleted: ${file}` });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}

// ─── PUT: Update memory ─────────────────────────────────────────────────────

export async function PUT(req: NextRequest) {
  try {
    const body = await req.json();
    const { id, content, tags, type, source } = body;

    if (!id) {
      return NextResponse.json({ success: false, error: 'ID required' }, { status: 400 });
    }

    const file = await findMemoryFileById(id);
    if (!file) {
      return NextResponse.json({ success: false, error: 'Not found' }, { status: 404 });
    }

    const filepath = path.join(VAULT_DIR, file);
    const existingContent = await fs.readFile(filepath, 'utf-8');
    
    // Parse body from existing file
    const bodyMatch = existingContent.match(/^---\n[\s\S]*?\n---\n*([\s\S]*)/);
    const existingBody = bodyMatch ? bodyMatch[1].trim() : '';

    // Rebuild with updated fields
    const newEntry = {
      id,
      content: content || existingBody.replace(/^## .+\n*/, '').replace(/\*Source: .+$/, '').trim(),
      source: source || existingContent.match(/^source:\s*(.+)/m)?.[1] || 'overlord',
      type: type || existingContent.match(/^type:\s*(.+)/m)?.[1] || 'fact',
      tags: tags || (existingContent.match(/^tags:\s*\[(.+)\]/m)?.[1] || '').split(', ').filter(Boolean),
      timestamp: Date.now(),
    };

    const updatedMarkdown = memoryToMarkdown(newEntry);
    await fs.writeFile(filepath, updatedMarkdown, 'utf-8');

    // Trigger cognify
    await triggerCogneeSync();

    return NextResponse.json({
      success: true,
      message: `Updated: ${file}`,
      memory: { ...newEntry, filename: file },
    });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
