'use client';

import React, { useState } from 'react';
import {
  FileText, BarChart3, Headphones, Video, Sparkles,
  Loader2, Download, ExternalLink, BookOpen
} from 'lucide-react';
import { useUIStore } from '@/stores/uiStore';

type OutputFormat = 'report' | 'infographic' | 'podcast' | 'video';

interface ResearchProject {
  id: string;
  query: string;
  status: 'idle' | 'researching' | 'generating' | 'complete' | 'error';
  formats: OutputFormat[];
  results: Partial<Record<OutputFormat, string>>;
  createdAt: number;
}

const formatConfig: Record<OutputFormat, { label: string; icon: React.ElementType; color: string }> = {
  report: { label: 'Report', icon: FileText, color: 'text-[var(--info)]' },
  infographic: { label: 'Infographic', icon: BarChart3, color: 'text-[var(--accent)]' },
  podcast: { label: 'Podcast', icon: Headphones, color: 'text-[var(--warning)]' },
  video: { label: 'Video', icon: Video, color: 'text-[var(--success)]' },
};

interface ResearchMultiFormatProps {
  isOpen: boolean;
  onClose: () => void;
}

export function ResearchMultiFormat({ isOpen, onClose }: ResearchMultiFormatProps) {
  const [query, setQuery] = useState('');
  const [selectedFormats, setSelectedFormats] = useState<OutputFormat[]>(['report', 'infographic']);
  const [projects, setProjects] = useState<ResearchProject[]>([]);
  const [selectedProject, setSelectedProject] = useState<ResearchProject | null>(null);
  const addToast = useUIStore((s) => s.addToast);

  const toggleFormat = (format: OutputFormat) => {
    setSelectedFormats((prev) =>
      prev.includes(format) ? prev.filter((f) => f !== format) : [...prev, format]
    );
  };

  const startResearch = () => {
    if (!query.trim() || selectedFormats.length === 0) return;

    const project: ResearchProject = {
      id: `research_${Date.now()}`,
      query: query.trim(),
      status: 'researching',
      formats: [...selectedFormats],
      results: {},
      createdAt: Date.now(),
    };

    setProjects((prev) => [project, ...prev]);
    setSelectedProject(project);
    setQuery('');

    // Simulate research pipeline
    setTimeout(() => {
      setProjects((prev) =>
        prev.map((p) => (p.id === project.id ? { ...p, status: 'generating' } : p))
      );
      setSelectedProject((prev) => prev?.id === project.id ? { ...prev, status: 'generating' } : prev);

      // Simulate format generation
      setTimeout(() => {
        const results: Partial<Record<OutputFormat, string>> = {};
        selectedFormats.forEach((format) => {
          switch (format) {
            case 'report':
              results.report = `# Research Report: ${project.query}\n\n## Executive Summary\n\nBased on comprehensive analysis of current market data and trends...\n\n## Key Findings\n\n1. Market size is growing at 12% YoY\n2. Top 3 competitors hold 67% market share\n3. Emerging opportunity in underserved segments\n\n## Recommendations\n\n- Focus on differentiation through quality\n- Leverage digital channels for distribution\n- Build strategic partnerships\n\n*Generated by Research Agent*`;
              break;
            case 'infographic':
              results.infographic = 'https://placehold.co/800x1200/6366f1/ffffff?text=Infographic';
              break;
            case 'podcast':
              results.podcast = 'podcast_audio_url';
              break;
            case 'video':
              results.video = 'video_url';
              break;
          }
        });

        setProjects((prev) =>
          prev.map((p) =>
            p.id === project.id ? { ...p, status: 'complete', results } : p
          )
        );
        setSelectedProject((prev) =>
          prev?.id === project.id ? { ...prev, status: 'complete', results } : prev
        );
        addToast({ type: 'success', message: 'Research complete — all formats generated' });
      }, 2000);
    }, 1500);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex bg-[var(--bg)]">
      {/* Left panel */}
      <div className="w-80 border-r border-[var(--border)] flex flex-col bg-[var(--bg-secondary)]">
        <div className="flex items-center justify-between px-4 py-3 border-b border-[var(--border)]">
          <h2 className="text-sm font-semibold text-[var(--text)] flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-[var(--accent)]" />
            Research → Multi-Format
          </h2>
          <button onClick={onClose} className="p-1 rounded hover:bg-[var(--bg-tertiary)] text-[var(--text-muted)]">
            <ExternalLink className="w-4 h-4" />
          </button>
        </div>

        {/* New research form */}
        <div className="p-4 border-b border-[var(--border)] space-y-3">
          <textarea
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="What do you want to research?"
            rows={3}
            className="w-full px-3 py-2 text-xs rounded-lg bg-[var(--bg-tertiary)] border border-[var(--border)] text-[var(--text)] placeholder:text-[var(--text-muted)] focus:outline-none focus:border-[var(--accent)] resize-none"
          />

          <div>
            <label className="text-[10px] uppercase tracking-wider text-[var(--text-muted)] mb-2 block">Output Formats</label>
            <div className="grid grid-cols-2 gap-2">
              {(Object.entries(formatConfig) as [OutputFormat, typeof formatConfig[OutputFormat]][]).map(([format, config]) => {
                const Icon = config.icon;
                const selected = selectedFormats.includes(format);
                return (
                  <button
                    key={format}
                    onClick={() => toggleFormat(format)}
                    className={`flex items-center gap-2 px-3 py-2 text-xs rounded-lg border transition-colors ${
                      selected
                        ? 'border-[var(--accent)] bg-[var(--accent)]/10 text-[var(--accent)]'
                        : 'border-[var(--border)] text-[var(--text-muted)] hover:text-[var(--text)]'
                    }`}
                  >
                    <Icon className="w-3.5 h-3.5" />
                    {config.label}
                  </button>
                );
              })}
            </div>
          </div>

          <button
            onClick={startResearch}
            disabled={!query.trim() || selectedFormats.length === 0}
            className="w-full flex items-center justify-center gap-2 px-4 py-2 text-xs rounded-lg bg-[var(--accent)] text-white hover:bg-[var(--accent-hover)] disabled:opacity-30 transition-colors"
          >
            <Sparkles className="w-3.5 h-3.5" />
            Research & Generate
          </button>
        </div>

        {/* Project list */}
        <div className="flex-1 overflow-y-auto">
          {projects.length === 0 ? (
            <div className="p-6 text-center text-xs text-[var(--text-muted)]">
              <BookOpen className="w-8 h-8 mx-auto mb-2 opacity-30" />
              <p>No research projects yet</p>
            </div>
          ) : (
            projects.map((project) => (
              <button
                key={project.id}
                onClick={() => setSelectedProject(project)}
                className={`w-full text-left px-4 py-3 border-b border-[var(--border)] hover:bg-[var(--bg-tertiary)] transition-colors ${
                  selectedProject?.id === project.id ? 'bg-[var(--bg-tertiary)]' : ''
                }`}
              >
                <div className="text-xs font-medium text-[var(--text)] truncate">{project.query}</div>
                <div className="flex items-center gap-2 mt-1">
                  {project.status === 'researching' || project.status === 'generating' ? (
                    <span className="flex items-center gap-1 text-[10px] text-[var(--accent)]">
                      <Loader2 className="w-3 h-3 animate-spin" />
                      {project.status === 'researching' ? 'Researching...' : 'Generating...'}
                    </span>
                  ) : project.status === 'complete' ? (
                    <span className="text-[10px] text-[var(--success)]">Complete</span>
                  ) : (
                    <span className="text-[10px] text-[var(--text-muted)]">{project.status}</span>
                  )}
                  <span className="text-[10px] text-[var(--text-muted)]">
                    {project.formats.map((f) => formatConfig[f].label).join(', ')}
                  </span>
                </div>
              </button>
            ))
          )}
        </div>
      </div>

      {/* Right panel */}
      <div className="flex-1 flex flex-col">
        {selectedProject ? (
          <ProjectDetail project={selectedProject} />
        ) : (
          <div className="flex-1 flex items-center justify-center text-[var(--text-muted)]">
            <div className="text-center space-y-3">
              <Sparkles className="w-12 h-12 mx-auto opacity-20" />
              <p className="text-sm">Select a project or start new research</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function ProjectDetail({ project }: { project: ResearchProject }) {
  const [activeFormat, setActiveFormat] = useState<OutputFormat | null>(
    project.formats[0] || null
  );

  return (
    <div className="flex-1 flex flex-col">
      <div className="px-6 py-4 border-b border-[var(--border)]">
        <h3 className="text-lg font-semibold text-[var(--text)]">{project.query}</h3>
        <div className="flex items-center gap-2 mt-2">
          {project.formats.map((format) => {
            const config = formatConfig[format];
            const Icon = config.icon;
            const hasResult = project.results[format];
            return (
              <button
                key={format}
                onClick={() => setActiveFormat(format)}
                className={`flex items-center gap-1.5 px-3 py-1.5 text-xs rounded-lg transition-colors ${
                  activeFormat === format
                    ? 'bg-[var(--accent)] text-white'
                    : hasResult
                    ? 'bg-[var(--bg-tertiary)] text-[var(--text)] hover:bg-[var(--bg-secondary)]'
                    : 'bg-[var(--bg-tertiary)] text-[var(--text-muted)]'
                }`}
              >
                <Icon className="w-3.5 h-3.5" />
                {config.label}
                {!hasResult && project.status !== 'generating' && project.status !== 'researching' && (
                  <span className="w-1.5 h-1.5 rounded-full bg-[var(--text-muted)]" />
                )}
              </button>
            );
          })}
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-6">
        {project.status === 'researching' || project.status === 'generating' ? (
          <div className="flex items-center justify-center h-full">
            <div className="text-center space-y-4">
              <Loader2 className="w-10 h-10 mx-auto text-[var(--accent)] animate-spin" />
              <p className="text-sm text-[var(--text-muted)]">
                {project.status === 'researching' ? 'Researching topic...' : 'Generating outputs...'}
              </p>
            </div>
          </div>
        ) : activeFormat && project.results[activeFormat] ? (
          <div className="max-w-3xl mx-auto">
            {activeFormat === 'report' && (
              <div className="prose prose-sm prose-invert max-w-none">
                <pre className="text-sm text-[var(--text)] whitespace-pre-wrap font-mono bg-[var(--bg-secondary)] rounded-lg p-6 border border-[var(--border)]">
                  {project.results.report}
                </pre>
              </div>
            )}
            {activeFormat === 'infographic' && (
              <div className="text-center">
                <img
                  src={project.results.infographic}
                  alt="Infographic"
                  className="max-w-full rounded-lg border border-[var(--border)] mx-auto"
                />
                <a
                  href={project.results.infographic}
                  download
                  className="inline-flex items-center gap-2 mt-4 px-4 py-2 text-xs rounded-lg bg-[var(--bg-secondary)] border border-[var(--border)] text-[var(--text)] hover:bg-[var(--bg-tertiary)] transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  Download
                </a>
              </div>
            )}
            {activeFormat === 'podcast' && (
              <div className="max-w-md mx-auto text-center space-y-4">
                <Headphones className="w-16 h-16 mx-auto text-[var(--warning)] opacity-30" />
                <p className="text-sm text-[var(--text-muted)]">Podcast audio would play here</p>
                <div className="h-12 rounded-lg bg-[var(--bg-secondary)] border border-[var(--border)] flex items-center justify-center">
                  <div className="flex items-center gap-1">
                    {Array.from({ length: 40 }).map((_, i) => (
                      <div
                        key={i}
                        className="w-1 rounded-full bg-[var(--accent)]"
                        style={{ height: `${Math.random() * 30 + 4}px` }}
                      />
                    ))}
                  </div>
                </div>
              </div>
            )}
            {activeFormat === 'video' && (
              <div className="aspect-video max-w-2xl mx-auto rounded-lg border border-[var(--border)] bg-[var(--bg-secondary)] flex items-center justify-center">
                <div className="text-center space-y-2">
                  <Video className="w-12 h-12 mx-auto text-[var(--text-muted)] opacity-20" />
                  <p className="text-xs text-[var(--text-muted)]">Video player would appear here</p>
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="flex items-center justify-center h-full text-[var(--text-muted)]">
            <p className="text-sm">No output for this format yet</p>
          </div>
        )}
      </div>
    </div>
  );
}
