import React from 'react';
import { useTasteStore } from '@/stores/tasteStore';
import { Palette, Wand2, ScanSearch, Info, CheckCircle2 } from 'lucide-react';

export const TastePanel: React.FC = () => {
  const { profile, isLoading, setLoading, setError, setProfile } = useTasteStore();

  const analyzeTaste = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch('/api/taste/analyze', { method: 'POST' });
      if (!response.ok) throw new Error('Failed to analyze taste');
      const data = await response.json();
      setProfile(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full w-full bg-zinc-900 text-zinc-100 p-6 space-y-6 rounded-xl border border-zinc-800">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-bold flex items-center gap-2">
          <Palette className="w-5 h-5 text-indigo-400" />
          Taste Learning
        </h2>
        <button 
          onClick={analyzeTaste} 
          disabled={isLoading}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 disabled:bg-zinc-700 text-white rounded-lg transition-colors text-sm font-medium"
        >
          {isLoading ? <ScanSearch className="w-4 h-4 animate-spin" /> : <ScanSearch className="w-4 h-4" />}
          Learn Taste
        </button>
      </div>

      {profile ? (
        <div className="flex-1 overflow-y-auto space-y-6 pr-2">
          <div className="p-4 bg-zinc-800 rounded-lg border border-zinc-700 space-y-4">
            <div className="flex items-center gap-2 text-sm font-semibold text-indigo-400">
              <Info className="w-4 h-4" />
              Preference Profile
            </div>
            <p className="text-xs text-zinc-400 italic">{profile.description}</p>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
              <div className="space-y-2">
                <div className="flex items-center gap-2 text-xs font-bold text-zinc-500 uppercase">Colors</div>
                <div className="flex flex-wrap gap-2">
                  {profile.rules.colors.map((color, i) => (
                    <span key={i} className="px-2 py-1 bg-zinc-700 rounded text-[10px] border border-zinc-600">{color}</span>
                  ))}
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex items-center gap-2 text-xs font-bold text-zinc-500 uppercase">Layouts</div>
                <div className="flex flex-wrap gap-2">
                  {profile.rules.layouts.map((layout, i) => (
                    <span key={i} className="px-2 py-1 bg-zinc-700 rounded text-[10px] border border-zinc-600">{layout}</span>
                  ))}
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex items-center gap-2 text-xs font-bold text-zinc-500 uppercase">Tone</div>
                <div className="flex flex-wrap gap-2">
                  {profile.rules.tone.map((t, i) => (
                    <span key={i} className="px-2 py-1 bg-zinc-700 rounded text-[10px] border border-zinc-600">{t}</span>
                  ))}
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex items-center gap-2 text-xs font-bold text-zinc-500 uppercase">Patterns</div>
                <div className="flex flex-wrap gap-2">
                  {profile.rules.patterns.map((p, i) => (
                    <span key={i} className="px-2 py-1 bg-zinc-700 rounded text-[10px] border border-zinc-600">{p}</span>
                  ))}
                </div>
              </div>
            </div>
          </div>

          <div className="p-4 bg-indigo-900/20 rounded-lg border border-indigo-500/30 space-y-3">
            <div className="flex items-center gap-2 text-sm font-semibold text-indigo-300">
              <Wand2 className="w-4 h-4" />
              Apply Taste
            </div>
            <p className="text-xs text-zinc-400">
              Learned preferences will be applied to new UI components generated by the agent.
            </p>
            <button className="w-full py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-xs font-medium transition-colors">
              Apply to Next Generation
            </button>
          </div>
        </div>
      ) : (
        <div className="h-full flex flex-col items-center justify-center text-zinc-500 space-y-2">
          <Palette className="w-12 h-12 opacity-20" />
          <p>No taste profile learned yet. Run analysis to extract patterns.</p>
        </div>
      )}
    </div>
  );
};
