name: Deploy to Overlord
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Pull & restart on Overlord machine
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install

      - name: Restart Application
        run: |
          pm2 restart overlord || pm2 start npm --name "overlord" -- run dev
